### ISSUE TITLE
step 5 and 6 

### ISSUE THREAD

**Issue by SquirrelTactics** [joshellissh/PiDGC#2]
So I moved over the config and board configurations to a new buildroot repo. and everything seems to be working but I'm to step 5 and not sure how to proceed from here. I have have QT creator installed with the free license. I'm just new to this software and any information would be greatly appreciated.

**Comment by SquirrelTactics** [comment]
Also If I can confirm that this does work then I can send you the new buildroot repo to post as a usable one since the older version no longer works.

**Comment by SquirrelTactics** [comment]
also I ran the build qt script everything looks good except for the ending of the script. here are the errors that I get. 
ot/output/qt/qt-everywhere-src-5.15.2/qtbase/src/corelib/codecs/qutfcodec.cpp
In file included from /home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/qfloat16.h:1,
                 from /home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/../../src/corelib/global/qendian.h:44,
                 from /home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/qendian.h:1,
                 from /home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/src/corelib/codecs/qutfcodec.cpp:43:
/home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/../../src/corelib/global/qfloat16.h:300:7: error: ‘numeric_limits’ is not a class template
  300 | class numeric_limits<QT_PREPEND_NAMESPACE(qfloat16)> : public numeric_limits<float>
      |       ^~~~~~~~~~~~~~
/home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/../../src/corelib/global/qfloat16.h:300:77: error: expected template-name before ‘<’ token
  300 | class numeric_limits<QT_PREPEND_NAMESPACE(qfloat16)> : public numeric_limits<float>
      |                                                                             ^
/home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/../../src/corelib/global/qfloat16.h:300:77: error: expected ‘{’ before ‘<’ token
/home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/../../src/corelib/global/qfloat16.h:344:18: error: ‘numeric_limits’ is not a class template
  344 | template<> class numeric_limits<const QT_PREPEND_NAMESPACE(qfloat16)>
      |                  ^~~~~~~~~~~~~~
/home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/../../src/corelib/global/qfloat16.h:344:69: error: ‘std::numeric_limits’ is not a template
  344 | template<> class numeric_limits<const QT_PREPEND_NAMESPACE(qfloat16)>
      |                                                                     ^
/home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/../../src/corelib/global/qfloat16.h:300:7: note: previous declaration here
  300 | class numeric_limits<QT_PREPEND_NAMESPACE(qfloat16)> : public numeric_limits<float>
      |       ^~~~~~~~~~~~~~
/home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/../../src/corelib/global/qfloat16.h:345:28: error: expected template-name before ‘<’ token
  345 |     : public numeric_limits<QT_PREPEND_NAMESPACE(qfloat16)> {};
      |                            ^
/home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/../../src/corelib/global/qfloat16.h:346:18: error: ‘numeric_limits’ is not a class template
  346 | template<> class numeric_limits<volatile QT_PREPEND_NAMESPACE(qfloat16)>
      |                  ^~~~~~~~~~~~~~
/home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/../../src/corelib/global/qfloat16.h:346:72: error: ‘std::numeric_limits’ is not a template
  346 | template<> class numeric_limits<volatile QT_PREPEND_NAMESPACE(qfloat16)>
      |                                                                        ^
/home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/../../src/corelib/global/qfloat16.h:300:7: note: previous declaration here
  300 | class numeric_limits<QT_PREPEND_NAMESPACE(qfloat16)> : public numeric_limits<float>
      |       ^~~~~~~~~~~~~~
/home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/../../src/corelib/global/qfloat16.h:347:28: error: expected template-name before ‘<’ token
  347 |     : public numeric_limits<QT_PREPEND_NAMESPACE(qfloat16)> {};
      |                            ^
/home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/../../src/corelib/global/qfloat16.h:348:18: error: ‘numeric_limits’ is not a class template
  348 | template<> class numeric_limits<const volatile QT_PREPEND_NAMESPACE(qfloat16)>
      |                  ^~~~~~~~~~~~~~
/home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/../../src/corelib/global/qfloat16.h:348:78: error: ‘std::numeric_limits’ is not a template
  348 | template<> class numeric_limits<const volatile QT_PREPEND_NAMESPACE(qfloat16)>
      |                                                                              ^
/home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/../../src/corelib/global/qfloat16.h:300:7: note: previous declaration here
  300 | class numeric_limits<QT_PREPEND_NAMESPACE(qfloat16)> : public numeric_limits<float>
      |       ^~~~~~~~~~~~~~
/home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/../../src/corelib/global/qfloat16.h:349:28: error: expected template-name before ‘<’ token
  349 |     : public numeric_limits<QT_PREPEND_NAMESPACE(qfloat16)> {};
      |                            ^
In file included from /home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/qendian.h:1,
                 from /home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/src/corelib/codecs/qutfcodec.cpp:43:
/home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/../../src/corelib/global/qendian.h: In static member function ‘static constexpr QSpecialInteger<S> QSpecialInteger<S>::max()’:
/home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/../../src/corelib/global/qendian.h:331:30: error: ‘std::numeric_limits’ is not a template
  331 |     { return QSpecialInteger(std::numeric_limits<T>::max()); }
      |                              ^~~
/home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/../../src/corelib/global/qendian.h:331:54: error: incomplete type ‘std::numeric_limits’ used in nested name specifier
  331 |     { return QSpecialInteger(std::numeric_limits<T>::max()); }
      |                                                      ^~~
/home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/../../src/corelib/global/qendian.h: In static member function ‘static constexpr QSpecialInteger<S> QSpecialInteger<S>::min()’:
/home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/../../src/corelib/global/qendian.h:333:30: error: ‘std::numeric_limits’ is not a template
  333 |     { return QSpecialInteger(std::numeric_limits<T>::min()); }
      |                              ^~~
/home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.15.2/qtbase/include/QtCore/../../src/corelib/global/qendian.h:333:54: error: incomplete type ‘std::numeric_limits’ used in nested name specifier
  333 |     { return QSpecialInteger(std::numeric_limits<T>::min()); }
      |                                                      ^~~
gmake: *** [Makefile:383: qutfcodec.o] Error 1
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.

#######################DONE##############################################
>>> Your QMake is ready on './qt-everywhere-src-5.15.2/aaaout/bin/qmake'
#######################DONE##############################################

**Comment by SquirrelTactics** [comment]
***** Update ****** 

The post-build.sh had the incorrect file path in it. the strip-all line has it pointed to a rpi3-display under source but it should read just display same for the cp line. 


#!/bin/sh

# Copy over binaries
echo "Optimizing display binary..."
strip --strip-all "../source/rpi3-display/display"
echo "Copying display binary to image..."
rm -f "$TARGET_DIR/root/display"
cp "../source/rpi3-display/display" "$TARGET_DIR/root/display"



I had the wrong version selected 5.15.2 instead of 5.12.2 but I'm still getting the same error. 



In file included from /usr/include/c++/11/algorithm:62,
                 from /home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.12.2/qtbase/include/QtCore/../../src/corelib/global/qglobal.h:142,
                 from /home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.12.2/qtbase/include/QtCore/qglobal.h:1,
                 from /home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.12.2/qtbase/include/QtCore/../../src/corelib/tools/qchar.h:43,
                 from /home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.12.2/qtbase/include/QtCore/qchar.h:1,
                 from /home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.12.2/qtbase/include/QtCore/../../src/corelib/tools/qstring.h:48,
                 from /home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.12.2/qtbase/include/QtCore/qstring.h:1,
                 from /home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.12.2/qtbase/src/corelib/codecs/qutfcodec_p.h:55,
                 from /home/justin/buildroot/buildroot/output/qt/qt-everywhere-src-5.12.2/qtbase/src/corelib/codecs/qutfcodec.cpp:41:
/usr/include/c++/11/bits/stl_algo.h:3455:5: note: ‘std::min’ declared here
 3455 |     min(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
gmake: *** [Makefile:378: qutfcodec.o] Error 1
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.

#######################DONE##############################################
>>> Your QMake is ready on './qt-everywhere-src-5.12.2/aaaout/bin/qmake'
#######################DONE##############################################

**Comment by SquirrelTactics** [comment]
Did you build this off of a windows 5.12.2 and then use wsl to run the Buildroot and static build? If so maybe it’s something to do with that. I’m building off of a Ubuntu VM. That’s the only thing I can think of if that is how you built it. Any ideas would be greatly appreciated since I’m so close to having this working.

**Comment by SquirrelTactics** [comment]
sorry i see that you built it off of 5.15.2 I still ran into the issue where it does not make the qmake in aaout it fails at that location. I did try and switch it to 5.15.6 opensource and it worked and built out the Qmake. but when I set the version in qtcreator to that qmake it says that its not a supported version. I'm so close to having this working please help.

**Comment by SquirrelTactics** [comment]
From what I have read qt 5.15.2 is not opensource anymore is there a way to build this on 5.15.6? when I try to just build from source it asks for a pro license

**Comment by SquirrelTactics** [comment]
Okay sorry for the many post but I have  figured out that you can install 5.15.2 from the archived online installer but I don't think that helps the other situation with the script to build the cross compile qmake

**Comment by SquirrelTactics** [comment]
I have figured it out. 

The solution is use Debian 11 VM and make sure that it's using GCC -9 not 10 there are issues with the newer compiler and that is the problem in it's entirety. 

closing this thank you again for taking the time to make this project.

**Comment by Hanifudin95** [comment]
hello mate @SquirrelTactics 

I have some question
Have you been able to build this image and get it working on your Raspberry Pi 3? I am unable to make the image work on my Raspi.

Do you know how to do steps 5, 6, and 7? I am confused because in step 3 you get the Raspi image in /PiDGC/buildroot/output/images. How do I insert the compiled display.pro into the image from step 5?

Thanks in advance
